package se.jbee.game.scs.screen;

public interface GameScreen {

	int
		SCREEN_MAIN = 0,
		SCREEN_LOAD_GAME = 1,
		SCREEN_LOADING_GAME = 2,
		SCREEN_SAVE_GAME = 3,
		SCREEN_SAVING_GAME = 4,
		SCREEN_SETUP_GAME = 5,
		SCREEN_SETUP_PLAYER = 6,
		
		SCREEN_USER_SETTINGS = 7,
		SCREEN_BLANK = 8,
		SCREEN_ENCOUNTER = 9,
		
		SCREEN_GALAXY = 10,
		SCREEN_STAR_CLUSTER = 11,
		SCREEN_SOLAR_SYSTEM = 12,
		SCREEN_COLONY = 13,
		SCREEN_ORBIT = 14,
		SCREEN_SPACECRAFT = 15,
		SCREEN_FLEET = 16,
		SCREEN_RENAME = 17,
		SCREEN_ICON_INFO = 18;
}
