package se.jbee.game.scs.screen;

public interface GameScreen {

	int
		SCREEN_MAIN = 0,
		SCREEN_LOAD_GAME = 1,
		SCREEN_SAVE_GAME = 2,
		SCREEN_SAVING_GAME = 3,
		SCREEN_USER_SETTINGS = 4,
		SCREEN_RENAME = 5,
		
		SCREEN_GALAXY = 6,
		SCREEN_STAR_CLUSTER = 7,
		SCREEN_SOLAR_SYSTEM = 8,
		SCREEN_COLONY = 9,
		SCREEN_ORBIT = 10,
		SCREEN_SPACECRAFT = 11,
		SCREEN_FLEET = 12;
}
