package se.jbee.game.scs.screen;

public interface GameScreen {

	int
		SCREEN_MAIN = 0,
		SCREEN_LOAD_GAME = 1,
		SCREEN_LOADING_GAME = 2,
		SCREEN_ERROR = 3,
		SCREEN_SETUP_CONTROLLS = 4,
		SCREEN_SAVING_GAME = 5,
		SCREEN_SETUP_GAME = 6,
		SCREEN_SETUP_PLAYER = 7,

		SCREEN_USER_SETTINGS = 8,
		SCREEN_BLANK = 9,
		SCREEN_ENCOUNTER = 10,

		SCREEN_GALAXY = 11,
		SCREEN_STAR_CLUSTER = 12,
		SCREEN_SOLAR_SYSTEM = 13,
		SCREEN_COLONY = 14,
		SCREEN_ORBIT = 15,
		SCREEN_SPACECRAFT = 16,
		SCREEN_FLEET = 17,
		SCREEN_RENAME = 18,
		SCREEN_ICON_INFO = 19,
		SCREEN_TECH_WHEEL = 20;
}
