package se.jbee.game.scs.gfx;

/**
 * Contains all the type-like constants used in the context of game specific
 * graphics.
 */
public interface Gfx {

	/**
	 * Fonts
	 */
	int
	FONT_REGULAR = 0,
	FONT_LIGHT = 1,
	FONT_THIN = 2,
	FONT_DOTS = 3;
	
	/**
	 * Colors
	 */
	int
	COLOR_DEFAULT = 0,
	COLOR_TEXT_HIGHLIGHT = 1,
	COLOR_TEXT_NORMAL = 2,
	COLOR_TEXT_SPECIAL = 3,
	COLOR_SLOT_BORDER = 4,
	COLOR_SHIELD = 5,
	COLOR_ENERGY = 6,
	COLOR_WEAPON = 7,
	COLOR_CONTROL = 8,
	COLOR_DRIVE = 9,
	COLOR_AMP = 10
	;
	
	/**
	 * Backgrounds
	 */
	int
	BG_BLACK = 0,
	BG_SPACE = 1;
	
	/**
	 * Noises
	 */
	int
	NOISE_STAR_LARGE = 0,
	NOISE_STAR_SMALL = 1,
	NOISE_PLANET_LARGE = 2,
	NOISE_PLANET_SMALL = 3;
	
	/**
	 * Textures
	 */
	int
	TEXTURE_STAR_200x2000_LARGE = 0,
	TEXTURE_STAR_200x2000_SMALL = 1,
	TEXTURE_PLANET_200x2000_LARGE = 2,
	TEXTURE_PLANET_200x2000_SMALL = 3,
	TEXTURE_PLANET_600x600_LARGE = 4,
	TEXTURE_PLANET_600x600_SMALL = 5;
	
	/**
	 * Objects
	 */
	int
	OBJ_BACKGROUND = 1,
	
	OBJ_BORDER = 20,
	OBJ_FOCUS_LINE = 21,
	OBJ_FOCUS_BOX = 22,
	
	OBJ_TEXT = 30,
	
	OBJ_STAR = 40,
	OBJ_STAR_CLIP = 41,
	OBJ_PLANET = 42,
	OBJ_PLANET_CLIP = 43,
	OBJ_ORBIT_ARC = 44,
	OBJ_ROUTE = 45,
	
	OBJ_SLOT = 50,
	OBJ_COMPONENT = 51,
	OBJ_RESOURCE = 52,
	OBJ_ROCK = 53,
	
	OBJ_BUTTON_MORE = 60,
	OBJ_BUTTON_LESS = 61
	;
	
	/**
	 * Icons (Slots)
	 */
	int 
	ICON_SHIELD1 = 1,
	ICON_SHIELD2 = 2,
	ICON_SHIELD3 = 3,
	ICON_SHIELD4 = 4,
	ICON_SHIELD5 = 5,
	
	ICON_BEAM1 = 11,
	ICON_BEAM2 = 12,
	ICON_BEAM3 = 13,
	ICON_BEAM4 = 14,
	ICON_BEAM5 = 15,
	
	ICON_DRIVE1 = 21,
	ICON_DRIVE2 = 22,
	ICON_DRIVE3 = 23,
	ICON_DRIVE4 = 24,
	
	ICON_REACTOR1 = 31,
	ICON_REACTOR2 = 32,
	ICON_REACTOR3 = 33
	;
}
